### ISSUE TITLE
Add/Enable Issue

### ISSUE THREAD

**Issue by Shbounab** [ngld/OverlayPlugin#10]
Idk whats the issue here. but everything is run as admin and everything is unblocked
![ACT issue](https://user-images.githubusercontent.com/38062244/66788722-b0d94b80-eeb6-11e9-9313-03e8e96f561c.PNG)

**Comment by ngld** [comment]
Can you make a screenshot of your `%AppData%\Advanced Combat Tracker\OverlayPluginCef\x64` folder?
If you're not sure how to open that folder, copy that path, press Win+R, paste and press enter.

**Comment by TrentGear** [comment]
I just ran into the same issue, added plugin and went through the updating process and crashed out of ACT. Shot of the requested folder 
![CEFFolder](https://cdn.discordapp.com/attachments/633461540120428544/633461588468170756/unknown.png)

**Comment by ngld** [comment]
Oh, right. Sorry, forgot about this issue:
Please download the [MS Visual C++ Redistributable for Visual Studio 2019](https://aka.ms/vs/16/release/VC_redist.x64.exe) and install it.

**Comment by TrentGear** [comment]
That solved it for me, thanks for the quick reply.

**Comment by Shbounab** [comment]
![Over](https://user-images.githubusercontent.com/38062244/66792384-6cee4280-eec6-11e9-8b81-2d54c03abf23.PNG)

**Comment by Shbounab** [comment]
still same issue . installed MS visual but still no luck

**Comment by ngld** [comment]
Try restarting ACT. Do you have the following file? `C:\Windows\system32\msvcp140.dll`

Did you use the link I posted above to install the MSVCRT?
