### ISSUE TITLE
Not compatible with FFXIV patch 5.2

### ISSUE THREAD

**Issue by TheStackTraceWhisperer** [ngld/OverlayPlugin#103]
Seems that patch 5.2 broke the plugin.  Lots of `Failed to scan memory: charmapAddress, targetAddress` errors.  Causes CPU spiking.

**Comment by ngld** [comment]
I'll release a patch once the parser has been updated. I've fixed everything except enmity data. Depending on how long it takes to fix that, I might release an update without enmity and add it in another update.

**Comment by zeroxposur18** [comment]
ACT Plugin Beta was just Released now

**Comment by ngld** [comment]
And OverlayPlugin 0.13.3 was released about 30 minutes later.
