### ISSUE TITLE
Version 0.13.3 shows error logs with CN 5.1 client.

### ISSUE THREAD

**Issue by ShadyWhite** [ngld/OverlayPlugin#105]
![image](https://user-images.githubusercontent.com/44015352/75111235-95efc280-5672-11ea-8024-d8a81d9e049c.png)

**Comment by ngld** [comment]
Sorry about that. I rushed 0.13.3 a bit. I have to add checks to make it work with both 5.1 and 5.2. I think I'll have a fix out some time today.

**Comment by ShadyWhite** [comment]
> Sorry about that. I rushed 0.13.3 a bit. I have to add checks to make it work with both 5.1 and 5.2. I think I'll have a fix out some time today.

Thanks~And the new lable look is very clean,nice work!

**Comment by ngld** [comment]
Should be fixed in 0.13.5. Let me know if you still see errrors or CPU spikes.
