### ISSUE TITLE
Have to readd my selected overlay skin to make it work

### ISSUE THREAD

**Issue by speezspaghet** [ngld/OverlayPlugin#115]
Every time I restart ACT my overlay skin does not record anything even though ACT itself does so just fine. After removing and adding while online and not restarting ACT, it works again.

**Comment by ngld** [comment]
Are you using MopiMopi? Do you see any errors in the overlay log? That's the text area below the overlay settings. You can make it bigger by dragging the line at the top of the log.

**Comment by speezspaghet** [comment]
> Are you using MopiMopi?

I prefer using Ember, although I checked MopiMopi only to find the same results.

> Do you see any errors in the overlay log? That's the text area below the overlay settings. You can make it bigger by dragging the line at the top of the log.

I will paste the content of the log in the following:

> [27.02.2020 08:48:46] Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker\Plugins\OverlayPlugin für FFXIV
[27.02.2020 08:48:48] Info: InitPlugin: Initialized.
**[27.02.2020 08:50:20] Info: ZReorder: Fixed E.**
[27.02.2020 08:50:23] Info: Found enmity memory for 5.2.

The last two appeared right after attacking a dummy.

Edit: After restarting ACT while ingame, the same log was visible except for the **bold text**. Maybe that gives us a clue?

**Comment by ngld** [comment]
What's your plugin loader order? FFXIV, OverlayPlugin, ...?

Does the URL for Ember contain `?HOST_PORT=`?
Do the settings change when you you re-add the overlay? What happens if you just reload the overlay instead of re-adding it?

**Comment by speezspaghet** [comment]
> What's your plugin loader order? FFXIV, OverlayPlugin, ...?

The order starting from the top is: OverlayPlugin, ACTWebSocket, FFXIV_ACT_Plugin.

> Does the URL for Ember contain ?HOST_PORT=?

This is the URL I copied from the Ember settings: https://goldenchrysus.github.io/ffxiv/ember-overlay/

> Do the settings change when you you re-add the overlay?

No. Only its size and position which I think is normal when you add an overlay.

> What happens if you just reload the overlay instead of re-adding it?

Nothing, it just reloads. It does not record anything after that.

**Comment by ngld** [comment]
Change your load order to this: FFXIV_ACT_Plugin, OverlayPlugin, ACTWebSocket
Afterwards, disable ACTWebSocket unless you're sure you need it and restart ACT.
That will most likely fix your issue.

**Comment by speezspaghet** [comment]
> That will most likely fix your issue.

And indeed it has. Thank you very much for your help!
