### ISSUE TITLE
Add Chinese translation please

### ISSUE THREAD

**Issue by ShadyWhite** [ngld/OverlayPlugin#12]
Nice to see this amazing tweak update again.But could you please add Chinese translation？I can help with Chinese translation.

**Comment by ngld** [comment]
I'll add it. It might take a while to export the translatable text (and make some of the messages translatable in the first place) but I'll let you know once this is ready.

**Comment by ShadyWhite** [comment]
> I'll add it. It might take a while to export the translatable text (and make some of the messages translatable in the first place) but I'll let you know once this is ready.

Awesome，thanks a lot！

**Comment by ngld** [comment]
I'm pretty much done with my preparations. All translatable strings (and existing translations) are here: https://github.com/ngld/OverlayPlugin/blob/master/translations.json

If you could add the chinese translations to that files and submit a PR with the changes, that'd be great!
Let me know if you have any questions.

**Comment by ShadyWhite** [comment]
Pulled request.Done for Chinese translation except for log informations.
&nbsp;

发自我的iPhone  


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ngld"<notifications@github.com&gt;; 
发送时间: 2019年10月28日(星期一) 中午1:41
收件人: "ngld/OverlayPlugin"<OverlayPlugin@noreply.github.com&gt;; 
抄送: "ShadyWhite"<baixc@vip.qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ngld/OverlayPlugin] Add Chinese translation please (#12)




I'm pretty much done with my preparations. All translatable strings (and existing translations) are here: https://github.com/ngld/OverlayPlugin/blob/master/translations.json
 
If you could add the chinese translations to that files and submit a PR with the changes, that'd be great!
 Let me know if you have any questions.
 
&mdash;

**Comment by ngld** [comment]
The 0.9.0 release contains your translations. Let me know if there are any issues!

**Comment by Bluefissure** [comment]
Okay here's another question, how to apply this translation?
Do I need to rebuild from source with `zh-CN/OverlayPlugin.resources.dll`?
Can you add the i18n method in README?

**Comment by ngld** [comment]
.NET should automatically load the translation for your current UI language (usually set in your Windows settings).

**Comment by Bluefissure** [comment]
> .NET should automatically load the translation for your current UI language (usually set in your Windows settings).

Can I manually set which translation to use?

**Comment by ngld** [comment]
You can modify [`CultureInfo.CurrentUICulture`](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.currentuiculture?view=netframework-4.8) to change which translations are used but AFAIK there's currently no way to do that in ACT.
