### ISSUE TITLE
mopimopi preset - no resize arrow

### ISSUE THREAD

**Issue by Sythalin** [ngld/OverlayPlugin#126]
Even with Resizing Arrow enabled in the Overlay menu, there is no arrow on any of the corners to resize the window.

**Comment by ngld** [comment]
![2020-04-30_00-29-14](https://user-images.githubusercontent.com/5465775/80653135-c2acc580-8a79-11ea-9391-0bd5cb390cbf.png)

Looks fine to me.
Not sure why the arrow doesn't show up for you. However, if you enable the `Force white background` option in OverlayPlugin, you can resize the overlay even without the arrow.
