### ISSUE TITLE
add new preset

### ISSUE THREAD

**Issue by kalilistic** [ngld/OverlayPlugin#135]
I created an overlay and was hoping to add it to the presets for easier instructions for my users. I'm happy to raise a PR for this but I wanted to reach out to you first... as I'm not sure if you had any criteria for inclusion (e.g. popularity or longevity). Thanks!

**Comment by kalilistic** [comment]
https://github.com/ngld/OverlayPlugin/pull/136

**Comment by ngld** [comment]
Sorry for the late reply. RL kept me busy.
I don't have any special criteria besides that it has to work (I'll remove outdated presets). The preset list is supposed to serve as a central list of maintained overlays and to make overlays easier to find.
