### ISSUE TITLE
Error: GetJobSpecificData: None

### ISSUE THREAD

**Issue by Marscgm** [ngld/OverlayPlugin#156]
This spams in my log, several times a second.

Error: GetJobSpecificData: None

**Comment by ngld** [comment]
That sounds like a Cactbot error. Make sure you've updated Cactbot. FFXIV 5.3 changed the offset for job specific data.

**Comment by ngld** [comment]
Feel free to reopen if this error still happens with only the FFXIV and OverlayPlugin enabled.
