### ISSUE TITLE
presets.json only support MiniParse

### ISSUE THREAD

**Issue by DieMoe233** [ngld/OverlayPlugin#159]
https://github.com/ngld/OverlayPlugin/blob/17df0411f5c8964229429fec15b5cc362756fc87/OverlayPlugin.Core/Controls/NewOverlayDialog.cs#L224

**Comment by ngld** [comment]
I've never seen Label and SpellTimer overlays before and I didn't want to implement code that is never used. If someone wants to add a SpellTimer or Label preset, I'll add it.
