### ISSUE TITLE
fishing plugin

### ISSUE THREAD

**Issue by Ron-FX** [ngld/OverlayPlugin#161]
first: i play in german, in english this issue dont exist
if i have mooch and catch fishes with double hook at the next cast the parse dont turn back to previous window so i have to hook for coming back. with normal hook it works fine.i think there is an error because language. so i found this line in the fisher.js probably has to be changed:
'catch': /00:0843:Du hast (?:einen |eine )?.+?\s?([\w\s\-\'\.\d\u00c4-\u00fc]{3,})(?: | [^\w] |[^\w\s\-\'\u00c4-\u00fc].+ )\(\d/,
in my game chat is written this way for 2 fishes:
"Du ziehst 2  Genist-Blindmantas  mit einer Länge von 272,6 Ilmen an Land!"
for one it looks like
Du hast einen  Genist-Wolkenspalter (21,8 Ilme) gefangen.
hope you can help to improve your nice work :)

**Comment by ngld** [comment]
I'm pretty sure you're in the wrong repo. You're probably talking about [Cactbot](https://github.com/quisquous/cactbot). This plugin doesn't have a `fisher.js`.
