### ISSUE TITLE
After update, OBS overlay urls via WSServer sorta broken?

### ISSUE THREAD

**Issue by covad301** [ngld/OverlayPlugin#172]
I say sorta, because my issue is primarily with SkillDisplay and HorizonOverlay.  Here's the weird thing, it only works if I add a "/" at the end of the provided URLs from the drop down menu in plugin tab.

For example if WSServer is active and I copy the provided SkillDisplay url from the menu:

https://rawrington.github.io/SkillDisplay/?HOST_PORT=ws://127.0.0.1:10501

It will open up a blankpage >_>  It works fine however if I just simply add a "/" at the end of the URL:

https://rawrington.github.io/SkillDisplay/?HOST_PORT=ws://127.0.0.1:10501/

The same thing happens with HorizonOverlay.  It literally works just fine if I add "/"   In the case of HorizonOverlay, No Damage Data is sent until I literally add a Slash at the end of the URL.

The other overlays work fine as they stand.  Just weird that the only two I use often is the one that exhibit this weird behavior without the Slash.

Same behavior happens when I tested it with Shared Overlays (Cool feature BTW!)

Edit:  Again, not a huge issue, I'm just looking out for those in the streaming community that were looking for copy/paste solutions.

**Comment by ngld** [comment]
Should be fixed in 0.16.5.
