### ISSUE TITLE
overlay plugin not working

### ISSUE THREAD

**Issue by apolloaress** [ngld/OverlayPlugin#176]
![image](https://user-images.githubusercontent.com/71220810/93020271-5079ef00-f5dc-11ea-883a-10f8adf575ec.png)

**Comment by ngld** [comment]
Sorry for the late reply. Somehow your OverlayPlugin configuration was corrupted. That usually happens after a crash or if the PC wasn't shut down properly.
You can fix the error by going to `%AppData%\Advanced Combat Tracker\Config` and deleting the two `RainbowMage.OverlayPlugin...` files.
