### ISSUE TITLE
If you enable this plugin, Logitech device macro keys will not work

### ISSUE THREAD

**Issue by Crescr** [ngld/OverlayPlugin#178]
As the title says.
If you disable it in the Plugin Listing, your Logitech device will work.
If enabled, Logitech devices will not work.

The plugin hotkey settings are untouched and blank.
Please add a setting that does not hook the key on the plug-in side.

**Comment by ngld** [comment]
OverlayPlugin only registers the hotkeys a user configures in the overlay settings. By default it doesn't register any hotkeys.

Based on previous experience, Logitech's software gets confused by the overlays and thinks that ACT is the active game. Tell Logitech to activate the hotkeys for both FFXIV and ACT and everything should work as expected.
