### ISSUE TITLE
FFXIV 5.4 changed the offset for HP.

### ISSUE THREAD

**Issue by Squall-Leonhart** [ngld/OverlayPlugin#187]
Only shows 0/0.

was working last in 5.35 as it was reading Bozjan mob HP counts.

@ravahn you know the offsets right?, looks like the act hp overlay works.

**Comment by CyberiumShadow** [comment]
I think this is related but the Target Bar overlays are also broken (they don't show up)

**Comment by CyberiumShadow** [comment]
@Squall-Leonhart Looks like someone has the updated enmity offsets in https://github.com/ngld/OverlayPlugin/pull/184

**Comment by Squall-Leonhart** [comment]
i wasn't actually having enmity issues, just HP, the relative enmity values were working.

**Comment by Squall-Leonhart** [comment]
maybe its for absolute enmity?, they also uploaded for 5.3 and that never got added too.

**Comment by Smaugan** [comment]
Target bar overlays are also broken for me (not showing up at all)

**Comment by ngld** [comment]
Fixed in 0.16.5. Sorry for the long wait.
