### ISSUE TITLE
Combatant data should be an array

### ISSUE THREAD

**Issue by bsides** [ngld/OverlayPlugin#204]
Hi ngld,

I would like to make a request, to make the Combatant data an array. Right now its data structure is not good, it's an object of n strings with common data inside. By JSON standards, this would benefit a lot from being an array, one of the main benefits of it being a structure with a iterator.

What I'm asking is this, change from:

```json
Combatant: {
	"YOU": {
		// combat data
	},
	"Other Person": {
		// more combat data
	}
}
```

...to this:

```json
Combatant: [
	{
		// YOU combat data straight here
	},
	{
		// OTHER PERSON's combat data right here
	}
]
```

This way, I would just iterate through Combatant (or other name to make it retro compatible, like Combatants) and search whatever I would like to show.

Would that be possible? Could I help with a PR?

Thank you in advance.

**Comment by valarnin** [comment]
Where are you getting the Combatant data? Via OverlayPlugin's `getCombatants` call? If so, that code is defined here:

https://github.com/ngld/OverlayPlugin/blob/master/OverlayPlugin.Core/EventSources/MiniParseEventSource.cs#L245-L316

**Comment by bsides** [comment]
It is probably it. I don't know C# but I'll try to debug it locally to see what I can do. Thank you for pointing the direction!
