### ISSUE TITLE
Missing miniparse_debug.html file

### ISSUE THREAD

**Issue by thailyn** [ngld/OverlayPlugin#208]
The documentation page for Event Types says to look at the miniparse_debug.html file's source code to see the available fields for the `CombatData` event.  I can't find this file anywhere (not in this repo or in the `Advanced Combat Tracker` directory inside `AppData` on my computer, where it looks like all the built-in overlays are located.  Is it missing?  Could we get some additional documentation on the available fields?  Thanks.

**Comment by mcd8604** [comment]
it's here, not missing:
https://github.com/ngld/OverlayPlugin/blob/master/OverlayPlugin.Core/resources/miniparse_debug.html

**Comment by ngld** [comment]
I've added the file to the docs website and added a link to the docs instead of the filename. That should make this much easier.
