### ISSUE TITLE
Is there any ensured way to detect if my code is running in Plugin's CEF instead of common browsers?

### ISSUE THREAD

**Issue by dsrkafuu** [ngld/OverlayPlugin#217]
I'm currently using this:

```ts
function isOverlayCEF(): boolean {
  return !!(window as any).OverlayPluginApi;
}
```

Not sure if that's safe or not.

**Comment by DieMoe233** [comment]
给你一个建议，去discord抓他，不然你可能要等很久很久很久很久很久...

**Comment by ngld** [comment]
That's a good way to check for OverlayPlugin. Normal browsers should never have that property and OverlayPlugin will always set it (since a few overlays require it).
Sorry about the late reply, I haven't had much time for FFXIV or OverlayPlugin recently.
