### ISSUE TITLE
fatal error upon opening

### ISSUE THREAD

**Issue by vogt1291** [ngld/OverlayPlugin#231]
I am getting this error:
---------------------------
Fatal Error - Unhandled Exception
---------------------------
An unhandled exception has occurred.  ACT may close.
Press Ctrl-C to copy this MessageBox.

System.IO.FileNotFoundException - Could not load file or assembly 'CefSharp.Core.Runtime.dll' or one of its dependencies. The specified module could not be found.
   at CefSharp.Cef.RemoveDisposable(IDisposable item)

   at CefSharp.OffScreen.ChromiumWebBrowser.Finalize()

CefSharp.Cef, CefSharp.Core, Version=95.7.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
---------------------------
OK   
---------------------------

**Comment by ngld** [comment]
Either update to the latest OverlayPlugin or install https://aka.ms/vs/17/release/vc_redist.x64.exe and restart ACT.
