### ISSUE TITLE
Overlay not showing when Borderless windowed mode has focus

### ISSUE THREAD

**Issue by campbebj** [ngld/OverlayPlugin#238]
Overlay not showing when Borderless windowed mode has focus. might be a windows setting.. unsure if you have any insight to this. (yes i double checked im in borderless and not fullscreen)

**Comment by ngld** [comment]
Make sure that ACT is parsing the correct FFXIV process. If you have multiple FFXIV windows open, the overlays only show if the window that ACT is parsing is focused.
If the overlays aren't visible if you switch to ACT or run FFXIV in windowed mode, it's a different issue. For further help, please [join the ACT FFXIV Discord](https://discord.gg/ahFKcmx). You'll get faster replies there.
