### ISSUE TITLE
Storing values between sessions

### ISSUE THREAD

**Issue by ghost** [ngld/OverlayPlugin#245]
I'm working on a personal overlay and I am wondering if there's a way to preserve data so that if ACT restarts you can start from where you left. This can be in any form: config file, databsae file, etc.. as long as I can access and modify the file with javascript from within the overlay.. I couldn't find anything related in the documentation

**Comment by quisquous** [comment]
See the `loadData` and `saveData` handlers.  The targetbars use these if you need an example: https://github.com/ngld/OverlayPlugin/blob/master/OverlayPlugin.Core/resources/targetbars/targetbars.js#L1035-L1048
