### ISSUE TITLE
Failed to download CEF

### ISSUE THREAD

**Issue by icywinters** [ngld/OverlayPlugin#26]
![image](https://user-images.githubusercontent.com/28671629/68828881-84fbe200-067d-11ea-8edd-a695267ef0e5.png)
0.10.0 
Can't enable the plugin as CEF failed to download due to SSL/TLS related error. I have search for the issue and the answers told me it may be related to using an outdated version of .Net framework. 

However, I am using the latest version (4.8). I have already tried to repair the framework but I am still out of luck. I have no idea what is wrong with the connection, my ACT can self update without any problem but I can't download plugin update within ACT....

Is there any chance that I can download the CEF files manually to bypass this issue? Thank you

![image](https://user-images.githubusercontent.com/28671629/68829064-0fdcdc80-067e-11ea-8f84-af7f88b12c4c.png)

**Comment by ngld** [comment]
You can manually download the archive from the releases section. The current CEF download for x64 is [CefSharp-75.1.14](https://github.com/ngld/OverlayPlugin/releases/download/v0.7.0/CefSharp-75.1.14-x64.DO_NOT_DOWNLOAD). Download that archive, extract it using 7-Zip into `%AppData%\Advanced Combat Tracker\OverlayPluginCef\x64` and create a new text file in that folder called `version.txt` with `75.1.14` as the content, you should be able to start ACT.

Make sure you place the extracted files directly in the folder and not into a subfolder. If `%AppData%\Advanced Combat Tracker\OverlayPluginCef\x64\libcef.dll` exists, you've done it correctly.

**Comment by icywinters** [comment]
Thank you! It works perfectly!
