### ISSUE TITLE
[Question] Reasons for high data traffic

### ISSUE THREAD

**Issue by github-1348A55** [ngld/OverlayPlugin#262]
According to appnetworkcounter's monitoring ACT itself downloads about 1GB to 2GB data in More than half a day.
The only other plugins used are cactbot and Hojoring.
Is this high traffic volume due to the overlay plugin?

overlay plugin log will show the following error.
Error: Update for EnmityEventSource took too long, skipping overlapping tick!
This may appear more than once over time.

**Comment by EQAditu** [comment]
This is just a random guess... but if it is OverlayPlugin, my guess is whatever software you have isn't correctly accounting for the fact that the CEF process is transferring data to/from a local connection.  The "high data traffic" never leaves your computer, so shouldn't be counted as something abnormal.  1GB in 12 hours is 24KB/s?  Maybe a little more than I would expect from mini parse data, but multiple overlays could multiply that.

**Comment by github-1348A55** [comment]
> This is just a random guess... but if it is OverlayPlugin, my guess is whatever software you have isn't correctly accounting for the fact that the CEF process is transferring data to/from a local connection. The "high data traffic" never leaves your computer, so shouldn't be counted as something abnormal. 1GB in 12 hours is 24KB/s? Maybe a little more than I would expect from mini parse data, but multiple overlays could multiply that.

Thank you EQAditu for your reply... And I am sorry for the late reply.
The investigation was incomplete, but various subsequent checks revealed nothing unusual.
In addition to setting up too many overlays,
It occurs when communication fails due to home network security and attempts are repeated.
So I closed this post now.
