### ISSUE TITLE
How to reference FFXIV_ACT_Plugin.Common

### ISSUE THREAD

**Issue by xeropresence** [ngld/OverlayPlugin#4]
The act plugin has all the sub plugins now merged into the master plugin as resources. Is there a method to extract them so it can be used as a reference?

**Comment by xeropresence** [comment]
Ended up using https://github.com/G4224T/Fody-Costura-Decompress

Kinda a pita

**Comment by ngld** [comment]
Go to https://github.com/ravahn/FFXIV_ACT_Plugin/releases and look for `FFXIV_ACT_Plugin_SDK_x.x.x.x.zip`. Currently the latest SDK version is 2.0.2.5. Ravahn only uploads a new SDK archive if he changes the API so it's not normal that the newer releases don't have it.
I'll add that to the instructions.

That tool seems to kind of complicated compared to https://github.com/takeshixx/ILSpy-CosturaPlugin. With this one you can just right-click the FFXIV ACT plugin in ILSpy and tell it to decompress the Costura archives.
