### ISSUE TITLE
Allow overlays to specify a default size

### ISSUE THREAD

**Issue by quisquous** [ngld/OverlayPlugin#48]
From https://discordapp.com/channels/551474815727304704/551474815727304706/647901926683574334

@ngld: "The overlay would call `OverlayPluginApi.setDefaultSize(<width>, <height>);`  which resizes the overlay and sets an internal flag that the default size has been applied. All subsequent calls to that function will be ignored (since the flag is set)."

**Comment by ngld** [comment]
Presets can provide default sizes which IMO is a better solution to this problem (and was easier to implement).
