### ISSUE TITLE
Frame Drop from not being window focus FFXIV

### ISSUE THREAD

**Issue by kyouch** [ngld/OverlayPlugin#59]
Before these updates, everytime I clicked in my dps meter, i could change the size, click on settings and refresh etc without getting frame drops, now everytime I click at it the FFXIV gets frame drops like it isn't the focus window anymore, like alt + tab.

**Comment by ngld** [comment]
Which overlay are you using?

**Comment by kyouch** [comment]
I'm using Canis Minor 'https://github.com/canisminor1990/ffxiv-cmskin', but the release of 'SgLy' that is in the Pull requests session

**Comment by ngld** [comment]
Just a quick test: If you click the ACTWS checkbox and then enable `No Focus`, does it behave as expected?

**Comment by kyouch** [comment]
Yes, yes it does behave correctly. Thank you! :o

**Comment by ngld** [comment]
Okay, that means I messed that setting up for non-ACTWS overlays. It should be enabled by default for those. I'll fix it with the next update.

**Comment by pwilkowski** [comment]
There is something weird going on here. I was writing my player bar plugin but without checking 'ACTWS Compatibility' I was not able to gain focus on any of the input fields.

When I did checked it, suddenly all of my inputs started working properly. Then after unclicking it (unchecking) inputs still worked.

I do have this piece of code that suppose to enable focus when user enters config mode:

```ts
	toggleSettings() {
		console.log('toggle config');
		this.configVisible = !this.configVisible;
		(window as any).OverlayPluginApi.setAcceptFocus(this.configVisible);
	}
```

But it doesn't seems to be working at all.
