### ISSUE TITLE
ActWebsocket compat doesn't send character name.

### ISSUE THREAD

**Issue by Tylian** [ngld/OverlayPlugin#6]
Mostly a quality-of-life thing, but ActWebsocket sends the character name. MopiMopi uses this in place of YOU.

https://github.com/ZCube/ACTWebSocket/blob/1d89d850f95348a5b1504a25b2bd9eb8683703e4/ACTWebSocket.Core/Parse/LogParse.cs#L71-L76

**Comment by ngld** [comment]
Looks like I [implemented this for the ACTWS shim](https://github.com/ngld/OverlayPlugin/blob/master/OverlayPlugin.Core/Overlays/MiniParseOverlay.cs#L48) but forgot to add this for the actual WebSocket server. Thanks for the reminder!

**Comment by ngld** [comment]
Sorry this took so long. 0.6.0 (which I've just released) should fix this. Let me know if the problem still persists!

**Comment by Tylian** [comment]
Just tried it out, works fine now. Thanks a bunch for the hard work!
