### ISSUE TITLE
Enmity????

### ISSUE THREAD

**Issue by Kumicoo** [ngld/OverlayPlugin#63]
How do i add enmity? Cactbot guy says it's already in ngld overlay, but there IS NOT HTML FOR ENMITY?

How do i add it? where is enmity plugin+overlay??

**Comment by ShadyWhite** [comment]
![image](https://user-images.githubusercontent.com/44015352/70380012-bbbcd380-196f-11ea-80ba-bd3321021f1d.png)

**Comment by Kumicoo** [comment]
Which one do i add? none of those work...

**Comment by ShadyWhite** [comment]
How？They all work for me,try this.
![image](https://user-images.githubusercontent.com/44015352/70380068-7ea51100-1970-11ea-9b83-42ea2262b829.png)

**Comment by Kumicoo** [comment]
What am i doing wrong? there is no overlay... 
https://prnt.sc/q7nmp7

**Comment by Kumicoo** [comment]
This here is all i can see...

and as you see, i am fighting...

https://prnt.sc/q7nn5r

**Comment by ngld** [comment]
Click the `Force white background` to find and resize the overlay. If it doesn't display anything even while you're in combat, check the overlay log (the text box at the bottom) and paste the contents of that box here.

**Comment by ShadyWhite** [comment]
Why is the folder name EnmityPlugin? Did you rename it yourself?

**Comment by ngld** [comment]
Right, you'll have to use the files included in OverlayPlugin. Other files (unsurprisingly) won't work.

**Comment by Kumicoo** [comment]
ShadyWhite had the right thing.

I did not rename anything... but using the other enmity folder worked... thanks!

**Comment by ngld** [comment]
Great.

**Comment by Kumicoo** [comment]
This enmity looks different from old cactbot. is that how it is now, or can i get old cactbot look?

**Comment by ngld** [comment]
IIRC the look didn't change and Cactbot never had an enmity overlay so I'm not sure what you're looking for.

**Comment by Kumicoo** [comment]
Hmm no matter then, at least it works now. Thanks for the help and have a nice weekend

**Comment by Kumicoo** [comment]
It was like, no colours. Only enmity of the taget you looked at was shown in numbers. so you could compare how close you were to the tank / next best dps... that wasnt cactbot enmity?

**Comment by Kumicoo** [comment]
Ahh i found it... this one https://github.com/xtuaok/ACT_EnmityPlugin

Is it possible to only take over the overlay with your NGLD enmity?

**Comment by Kumicoo** [comment]
aka. this one (sorry for spamming, just wondering since i am colorblind and heavily prefer this) 

https://prnt.sc/q7o0lm

**Comment by ngld** [comment]
I'm pretty sure that the overlay currently looks like those screenshots. Have you tried the different `.html` files?

**Comment by Kumicoo** [comment]
it doesnt look like those, it looks like this

https://prnt.sc/q7o5x9
