### ISSUE TITLE
Invalid character in filename

### ISSUE THREAD

**Issue by Noirvent** [ngld/OverlayPlugin#67]
Hello,
Since last update, I've got an error loading overlays, but only when ACTWebSocket is checked, Kagerou DPS Overlay work, but not [cactbot](https://github.com/quisquous/cactbot).

Here's the error: 
```
[10.12.2019 21:00:22] Error: Error checking html rel dir: file:///G:/Games/Advanced%20Combat%20Tracker/cactbot/ui/oopsyraidsy/oopsyraidsy.html?HOST_PORT=ws://127.0.0.1/fake/: System.ArgumentException: Caractères non conformes dans le chemin d'accès.
   à System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   à System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   à Cactbot.CactbotEventSource.GetUserConfigDirAndFiles(String source, String& config_dir, Dictionary`2& local_files)
```
Translated it would means "illegal characters in path", the path being 
`file:///G:/Games/Advanced%20Combat%20Tracker/cactbot/ui/oopsyraidsy/oopsyraidsy.html?HOST_PORT=ws://127.0.0.1/fake/`

FFXIV_ACT_Plugin version: 2.0.4.6
OverlayPlugin version: 0.11.5.0
CactbotOverlay version: 0.13.2.0

**Comment by ngld** [comment]
That's a bug in Cactbot, not OverlayPlugin. Why are you clicking the ACTWS checkbox? You only need that for ACTWS overlays (MopiMopi and SkillDisplay). Kagerou and Cactbot work without that. In fact, just clicking the checkbox breaks Cactbot overlays.
