### ISSUE TITLE
Overlays disappear when ACT is minimised

### ISSUE THREAD

**Issue by RB2804** [ngld/OverlayPlugin#68]
When ACT is minimised, the overlay will disappear. I can still hear the alerts from the overlay and when I have the ACT window active again they will reappear. The strange thing is the ACT window doesn't even need to be focused, just not minimised to my taskbar. Only been happening since I moved over to the ngld overlayplugin.

**Comment by ngld** [comment]
I can't reproduce the issue. The overlays show fine as long as either ACT or the game is focused. Whether ACT is in the background or minimized doesn't seem to make a difference.

You can try disabling the `Hide overlays while the game is in the background` option and see if that helps.
