### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by HAERUHAERU** [ngld/OverlayPlugin#69]
![캡처](https://user-images.githubusercontent.com/23272956/70859882-80b53400-1f5d-11ea-9a73-5098c8b00219.PNG)

OverlayPlugin 0.11.5
message popup → act kill → restart act → download again...

![image](https://user-images.githubusercontent.com/23272956/70859972-cde5d580-1f5e-11ea-90c6-fac53e554fd0.png)

I apply this solution #26, it's works. but this message pop up. (Failed to check for updates:)
The previous version worked fine, what happened?

**Comment by ngld** [comment]
The first error is caused by loading ACTWebSocket before OverlayPlugin (ACTWS contains an old version of `SharpCompress` which is missing stuff that OverlayPlugin expects).

The second error is GitHub complaining about too many requests. Should be fine if you wait for a few minutes.

**Comment by HAERUHAERU** [comment]
Thanks a lot!
