### ISSUE TITLE
Miniparse event source doesn't save settings

### ISSUE THREAD

**Issue by quisquous** [ngld/OverlayPlugin#7]
This is with 0.6.0.  If I update the sorting and time, and then close ACT, it doesn't appear to save.

**Comment by ngld** [comment]
Can you check the config file to make sure that issue is saving and not loading? The file should be in `%AppData%\Advanced Combat Tracker\Config\RainbowMage.OverlayPlugin.config.json`.

**Comment by quisquous** [comment]
Excellent question.  It saves just fine, but does not load correctly.

**Comment by ngld** [comment]
Figured it out. I got the names wrong. The load function is looking for the private attribute names while the JSON encoder used the public property names. At least this will be an easy fix.
