### ISSUE TITLE
Potential race condition in common.js when loading a websocket overlay

### ISSUE THREAD

**Issue by ackwell** [ngld/OverlayPlugin#72]
There seems to be a somewhat-common error on page load:

```
Uncaught ReferenceError: msg is not defined
```

By the looks of it, it's likely caused when something tries to `sendMessage` while the queue is in-place, as it _looks_ like [line 14](https://github.com/ngld/OverlayPlugin/blob/master/docs/assets/shared/common.js#L14) has a typo (`s/msg/obj`)

Would PR but not sure on tooling for this 🙇

**Comment by ngld** [comment]
Thanks for catching this! I thought I fixed this mistake a while ago (I forgot to update that line after renaming the parameter) but apparently I didn't.... 

I haven't had time to properly setup a CI script with building, linting, etc.
Currently I just build the `common.min.js` manually through Terser. I know I should do this properly but this was faster... >_>
