### ISSUE TITLE
OverlayPlugin WSServer config links drop query param

### ISSUE THREAD

**Issue by quisquous** [ngld/OverlayPlugin#77]
There's a new select that I hadn't seen before on the bottom of the Plugins -> OverlayPlugin WSServer page.

If I click the URL, it opens up in a browser, but it drops all the url query parameters, so it's not in WS mode in the browser unless I add those manually.

**Comment by ngld** [comment]
Is the URL displayed correctly? Does right-click > Copy Link work?

**Comment by quisquous** [comment]
URL is correct.  Right-click copy does not work, as right click behaves like left click and opens the url.
