### ISSUE TITLE
Failed to download CEF

### ISSUE THREAD

**Issue by poisonousfaith** [ngld/OverlayPlugin#8]
On version 0.7.1, cannot use the plugin as the CEF fails no matter how many times I try to download it. Attempted on multiple internet connections.
![image](https://user-images.githubusercontent.com/56526780/66727347-d9931e00-ee81-11e9-879c-8226359430c4.png)

**Comment by ngld** [comment]
I should probably retry failed downloads (and keep the already downloaded data so it doesn't have to start over from the beginning).

Can you please test [this build](https://github.com/ngld/OverlayPlugin/files/3722820/OverlayPlugin-resume-test.zip)?
Just extract that into your existing OverlayPlugin directory and overwrite the files there.

**Comment by Poseidonine** [comment]
![Capture](https://user-images.githubusercontent.com/56569426/66794338-2a7d3380-eecf-11e9-9543-7958f4242ca2.PNG)

I also have similar problems.
I have also tried your test build. The results are the same.

**Comment by ngld** [comment]
I've released a [new version](https://github.com/ngld/OverlayPlugin/releases). Can you please test that?

**Comment by Poseidonine** [comment]
![Capture](https://user-images.githubusercontent.com/56569426/66799645-ef373080-eedf-11e9-98d9-2505f27cba80.PNG)
![Capture2](https://user-images.githubusercontent.com/56569426/66799646-efcfc700-eedf-11e9-9514-3838b5064245.PNG)

Second Image popped up at lower corner. Download seems to be interrupted.

**Comment by ngld** [comment]
Can you try downloading the release again? I think I've fixed it this time... I'm sorry this became so complicated.

**Comment by Poseidonine** [comment]
I am please to say that it is now working. And please do not apologize. I am aware that this is still in beta. Bugs and patches are part of process of a great application.

Thank You! The community appreciates your hard work. Keep it up!

**Comment by ngld** [comment]
The last issue was due to a stupid mistake on my part. If I had actually tested it before releasing, I would've caught that so I kind of felt compelled to apologize.
Anyway, thanks for the confirmation and praise. ^^
