### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by illyav-d** [ngld/OverlayPlugin#9]
Hi!
Thanks for your work!
I'm having issues with build.bat file.
I installed Windows Build tools 2013 and after that Visual Studio 2019 (I tried to run it after installing Build Tools but no luck so thought visual studio would fix it)
Rebooted, launched as admin.
Sorry if I overlooked something simple but pretty sure I did all the nessecary stuff.
I will attach a pic below.
![image](https://user-images.githubusercontent.com/56565035/66785710-57851280-eede-11e9-917d-95c645a3315d.png)

**Comment by ngld** [comment]
`The imported project "...\Microsoft.CSharp.Core.targets" was not found.`
Did you install the C# / .NET stuff?

![ngldox_2019-10-15_02-23-43](https://user-images.githubusercontent.com/5465775/66791060-d126fb80-eef2-11e9-8c52-0bf2c68e7e35.png)

If you just want to use the plugin, you can find precompiled versions on the [release page](https://github.com/ngld/OverlayPlugin/releases). Just click on the "Assets" link for the newest release.

**Comment by illyav-d** [comment]
I'm dumb, ty! :)
