### ISSUE TITLE
Crashes ACT when enabled as of Version 2.0.5.0 of the FFXIV Parsing Plugin

### ISSUE THREAD

**Issue by SolarMisae** [ngld/OverlayPlugin#98]
After updating this and the latest FFFXIV parsing plugin, when loading the OverlayPlugin DLL to ACT, the program crashes shortly after with this error message.
![overlayplugin_error](https://user-images.githubusercontent.com/54002936/73046802-73834300-3e41-11ea-9715-0cf60dff5ba6.PNG)

I know absolutely nothing but in the error message I think I see it's trying to load the old parsing plugin from June 2019 for some reason? (Version 2.0.2.2)

**Comment by ngld** [comment]
No, that's the minimum supported version. The error nessage appears because the FFXIV plugin isn't enabled.

**Comment by SolarMisae** [comment]
I see, but the plugin is indeed enabled. The FFXIV plugin that is. It's working now though, but it took me reinstalling everything from the ground up. Note for anyone else having this issue.
